Lambda-School-Labs/city-data-comparison-fe

src/App.scss
src/components/navigation/Navigation.js

-Fixes disappearing links
-resizes data to 100% at mobile width, flips to column with burger data nav

fixes disappearing sub-500px nav links

---

src/components/Map.js
src/components/map-components/DataDisplay.js
src/components/map-components/Map.scss

Burger close is still a lil buggy

Map - Responsive styling fixes in datadisplay

---

src/App.scss
src/components/dashboard/Dashboard.js

Added back animations and added a media query so animations display more promptly when screen width goes to or below 500px

Dashboardanimations

---

src/components/dashboard/Dashboard.js

Adds anchor and link to compare window - Just a humble man making humble commits

ADDS bookmark redirect to compare button

---

src/components/map-components/Map.scss

Now the datanav grows and shrinks when the menu hamburger whatever is opened/closed

fixed mobile animations on datanav

---

package.json
src/App.js

I'm a GA noob - I think this is set up properly, but I don't think I can check when running locally? I'm not sure - I'm using a site that's new to me and a library that abstracts it further - thinking this will track visitors to the main page when it's on a deployment. After that we will have to build in "events" to track specific user behavior (similar to following format)
`ReactGA.event({
category: 'Search',
action: 'search for ${search}'
});`
Let's not put the cart before the horse though - this assumes that this initial GA works at all.

Implements basic google analytics

---

src/App.js
src/components/Map.js

I think analytics get tripped up by adblockers - my use of Brave browser has been a tax on my Lambda experience more times than I can count
-there is as yet only one event logged, when a city is selected or deselected from the map - we'll see what sorts of data we get by default -  I think pageview analytics on different "pages" (map, profile, login/signup) will be end up being essential

Analytics working

---

src/components/Map.js
src/components/forms/buttons/Google.js
src/components/navigation/Footer.js

Hopefully this solves the data issues

adds https

---

README.md
src/App.js
src/components/Map.js
src/components/dashboard/Dashboard.js
src/components/map-components/DataDisplay.js
src/components/map-components/MapSearch.js
src/components/map-components/Markers.js
src/components/navigation/Footer.js
src/components/navigation/Navigation.js

- Maps selected cities outside of deterministic zoom scope
- Expands search set
- Testing needed - Select cities you've lived and see if they work
TODO:
Add deselect functionality to selected in sidenav (If we decide to keep)
Add deselect functionality to selected map markers

- Expands and handles larger search set

---

src/App.js
src/components/Callback.js
src/components/navigation/Navigation.js
src/components/user-profile/Favorites.js

This updates the profile page to have a favorites bit, initializes userContext on login, and updates the navbar if the user is logged in

Profilefavs

---

src/components/forms/buttons/Facebook.js
src/components/forms/buttons/Google.js
src/components/forms/buttons/Linkedin.js
src/components/user-profile/ProfileCard.js
yarn.lock

Sorry about that. Facebook works with localhost but I bet when we merge it It wont work because of unsecure/https stuff in which case I think we should use twitter instead of facebook.

media buttons fixed.

---

src/components/graphs/GeneralStats.js

fixed hardcoded income

---

src/components/navigation/Footer.js

User feedback included a roast on how we weren't a "personalized city" application just yet. Changed the footer CTA to reflect that.

changed footer CTA because of user feedback

---

src/components/dashboard/Dashboard.js
src/components/map-components/FavoriteButton.js
src/components/navigation/Navigation.js
src/components/user-profile/ProfileCard.js

This improves the consistency with which userImage is handled - Previously it was being alternatively set to a string and an object, and when spread into a new object, spreading the string, with humorous results.
There is reference to a key on it named userimage as well as usersimage - These seem to refer to the same data and should probably be consolidated to a single key name. That said, the avatar upload seems fully functional (on the front end - backend still needs to handle deleting an avatar before saving a new one) and Not Ugly at the moment, which is key

Broken image fix

---

src/components/Callback.js

hotfix for userobject

---

src/components/user-profile/ProfileCard.js

Added function where onSubmit is to make the update user so that it does not execute everytime when the page loads

Fixed Image not displaying @ nav

---

src/App.js
src/components/Callback.js
src/components/map-components/DataDisplay.js
src/components/map-components/FavoriteButton.js

-Expands analytics events to include user flow events
-fixes X button per Luke catch (Thank you Luke for the reminder!)
-Tweaks map zoom to fill container

User analytics + a tweak and a bugfix

---

src/components/graphs/culture/birthRateCard.js
src/components/graphs/culture/tempAvg.js
src/components/graphs/economics/TravelTimeCard.js
src/components/graphs/transportationScore.js
src/components/map-components/DataDisplay.js
src/components/map-components/Map.scss

RESPONSIVE STYLING IS DONE BABY

Map styling

---

src/components/graphs/culture/PopulationGraph.js
src/components/graphs/housing/House_price.js

Super small changes but they add some polish

formats y axis ticks with $ and some commas

---

package.json
src/App.js
src/components/dashboard/Dashboard.js
src/index.js

Not much to see here - completes a project stretch goal by implementing sentry.io. 
ALERT: Adds some new packages!

Exception monitoring

---

src/App.scss
src/components/user-profile/ExpandIcon.js
yarn.lock

Nav spacing

---

src/App.scss
src/components/map-components/Markers.js
src/components/map-components/PopupMap.js
yarn.lock

This was something we discussed at some point I believe. If not, don't merge it.

disabled popupmap on mobile/tablet views

---

src/App.scss
src/components/graphs/culture/tempAvg.js
src/components/graphs/housing/OwnerCostCard.js
src/components/modal/SmocCard.js
src/components/modal/modal.scss
src/components/modal/smocModule.js
src/components/user-profile/ExpandIcon.js
yarn.lock

changed to Max temperature per Scott and added Smoc Module when clicked instead of going to other page.

Temp + smoc

---

src/App.scss
src/components/graphs/culture/tempAvg.js
src/components/graphs/housing/OwnerCostCard.js
src/components/map-components/Markers.js
src/components/modal/SmocCard.js
src/components/modal/modal.scss
src/components/modal/smocModule.js
src/components/user-profile/ExpandIcon.js
yarn.lock

bad cursor shows up now Works with zoom and seearching cities/deselecting cities on legend. Only thing that happens is when you do deselect that 3rd city it shows that bad cursor until you hover away from it and then its right back to normal

Array alert

---

src/App.js
src/components/graphs/Recommendations.js
src/components/graphs/housing/House_price.js
src/components/map-components/DataDisplay.js
src/components/map-components/Markers.js

Ui fixes 1 31

---

src/components/graphs/housing/House_price.js

This fixes null being rounded to 0 by Math.floor() - my bad

Pre release bugfixes

---

README.md
src/components/user-profile/ProfileCard.js
src/components/user-profile/profile.scss

Fixes up profile styles, fixes image upload breaking profile avatar briefly

fixed upload breaking image and touched up styles

---

src/App.js
src/components/aboutus/Member.js
src/components/aboutus/aboutus.scss
src/components/axiosAuth.js
src/components/user-profile/profile.scss

Portfolio link fix

---

src/App.scss
src/components/Map.js
src/components/aboutus/team.js
src/components/dashboard/Dashboard.js
src/components/dashboard/assets/seconddiv.svg
src/components/legal/ColoredScrollbars.js
src/components/legal/privacy.scss
src/components/map-components/DataDisplay.js
src/components/map-components/Map.scss
src/components/map-components/PopupMap.js
src/components/map-components/assets/helpcircle.svg
src/components/navigation/Navigation.js
src/components/user-profile/profile.scss

updated styling on data overview page, colors, about page bios

Scp filter

---

src/components/graphs/housing/House_price.js
src/redux/actions/cityActions.js

Bug fix for a problem with the date labels in the housing price graph.=
Fixes # (issue)
The problem was the graph not displaying correct dates when two different cities, with different start dates to their housing prices, were selected.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

fixes bug with date labeling in the housing price graph

---

src/utils/axiosDataScience.js

This updates the frontend to the new data science deployment.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

Updates API to new data science deployment
